#!/usr/bin/env bash
# Composer DAG backup utility
# Author: LIM UI JIN
#
# Downloads the Composer dags directory and creates a timestamped .tgz archive.
#
# Usage:
#   ./backup-dags.sh
#   ./backup-dags.sh gs://BUCKET/dags /path/to/backup
#
# Environment overrides:
#   COMPOSER_DAGS_URI=gs://BUCKET/dags
#   BACKUP_DIR=/path/to/backup
#   RETENTION_DAYS=30        # 0 disables cleanup

set -Eeuo pipefail

DEFAULT_DAGS_URI="gs://asia-northeast3-airflow-pro-0fc91c4e-bucket/dags"
COMPOSER_DAGS_URI="${1:-${COMPOSER_DAGS_URI:-$DEFAULT_DAGS_URI}}"
BACKUP_DIR="${2:-${BACKUP_DIR:-$PWD}}"
RETENTION_DAYS="${RETENTION_DAYS:-30}"

TIMESTAMP="$(date '+%Y%m%d_%H%M%S')"
WORK_DIR="$(mktemp -d "${TMPDIR:-/tmp}/composer-dags-backup.XXXXXX")"
STAGE_DIR="$WORK_DIR/dags"
ARCHIVE_NAME="dags-${TIMESTAMP}.tgz"
ARCHIVE_PATH="$BACKUP_DIR/$ARCHIVE_NAME"

cleanup() {
  rm -rf "$WORK_DIR"
}
trap cleanup EXIT

log() {
  printf '[%s] %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$*"
}

command -v gcloud >/dev/null 2>&1 || {
  echo "ERROR: gcloud command not found." >&2
  exit 1
}
command -v tar >/dev/null 2>&1 || {
  echo "ERROR: tar command not found." >&2
  exit 1
}

[[ "$COMPOSER_DAGS_URI" == gs://*/dags || "$COMPOSER_DAGS_URI" == gs://*/dags/ ]] || {
  echo "ERROR: COMPOSER_DAGS_URI must be a gs://.../dags path: $COMPOSER_DAGS_URI" >&2
  exit 1
}

mkdir -p "$BACKUP_DIR"

log "Source  : $COMPOSER_DAGS_URI"
log "Archive : $ARCHIVE_PATH"

# Copy into an isolated temporary directory so an old local ./dags directory
# cannot be mixed into the new backup.
mkdir -p "$STAGE_DIR"
gcloud storage cp --recursive "${COMPOSER_DAGS_URI%/}/*" "$STAGE_DIR/"

# Refuse to create a misleading empty backup.
if ! find "$STAGE_DIR" -mindepth 1 -print -quit | grep -q .; then
  echo "ERROR: No DAG files were downloaded; archive was not created." >&2
  exit 1
fi

tar -C "$WORK_DIR" -czf "$ARCHIVE_PATH" dags

# Verify gzip/tar integrity before reporting success.
tar -tzf "$ARCHIVE_PATH" >/dev/null
ARCHIVE_SIZE="$(du -h "$ARCHIVE_PATH" | awk '{print $1}')"
log "Backup completed: $ARCHIVE_NAME ($ARCHIVE_SIZE)"

# Optional retention cleanup for archives generated by this script.
if [[ "$RETENTION_DAYS" =~ ^[0-9]+$ ]] && (( RETENTION_DAYS > 0 )); then
  find "$BACKUP_DIR" -maxdepth 1 -type f -name 'dags-*.tgz' \
    -mtime "+$RETENTION_DAYS" -print -delete
fi
